AllCops:
  Exclude:
    - bin/**/*
    - config/**/*
    - db/**/*
    - spec/dummy/**/*
    - vendor/**/*
  RunRailsCops: true

Documentation:
  Exclude:
    - spec/**/*

SpaceInsideStringInterpolation:
  EnforcedStyle: space
